let currentTab = 'all';

// --- ABDULLAH KÖKSAL'S MASTER DATABASE (500+ Entries) ---
const synapseDatabase = [
    { id: 1, text: "Britleness", meaning: "Kırılganlık", category: "technical", type: "word" },
    { id: 2, text: "Density", meaning: "Yoğunluk", category: "technical", type: "word" },
    { id: 3, text: "Hardness", meaning: "Sertlik", category: "technical", type: "word" },
    { id: 4, text: "Infrastructure", meaning: "Altyapı", category: "technical", type: "word" },
    { id: 5, text: "Circular Polarization", meaning: "Dairesel Polarizasyon", category: "technical", type: "word" },
    { id: 6, text: "Impedance Matching", meaning: "Empedans Uyumu", category: "technical", type: "word" },
    { id: 7, text: "The system utilizes RTK for centimeter-level accuracy.", meaning: "Sistem, santimetre seviyesinde doğruluk için RTK kullanır.", category: "technical", type: "sentence" },
    { id: 8, text: "Collaborate", meaning: "İş birliği yapmak", category: "daily", type: "word" },
    { id: 9, text: "Deadline", meaning: "Son teslim tarihi", category: "daily", type: "word" },
    { id: 10, text: "I am highly motivated to work on autonomous systems.", meaning: "Otonom sistemler üzerinde çalışmak için oldukça motivasyonluyum.", category: "daily", type: "sentence" },
    { id: 11, text: "Versatile", meaning: "Çok yönlü (Hem araçlar hem insanlar için kullanılır)", category: "daily", type: "word" },
    { id: 12, text: "Feasible", meaning: "Yapılabilir / Uygulanabilir ", category: "daily", type: "word" },
    { id: 13, text: "Ambiguous", meaning: "Belirsiz", category: "daily", type: "word" },
    { id: 14, text: "Prioritize", meaning: "Önceliklendirmek", category: "daily", type: "word" },
    { id: 15, text: "Reliability", meaning: "Güvenilirlik", category: "daily", type: "word" },
    { id: 16, text: "Obstacle", meaning: "Engel / Mani", category: "daily", type: "word" },
    { id: 17, text: "Innovation", meaning: "Yenilikçilik / İnovasyon", category: "daily", type: "word" },
    { id: 18, text: "Enhance", meaning: "Geliştirmek / Kalitesini artırmak", category: "daily", type: "word" },
    { id: 19, text: "Implement", meaning: "Uygulamaya koymak / Yürütmek", category: "daily", type: "word" },
    { id: 20, text: "Precise", meaning: "Kesin", category: "daily", type: "word" },
    { id: 21, text: "Mitigate", meaning: "Hafifletmek / Etkisini azaltmak (Risk veya gürültü için)", category: "daily", type: "word" },
    { id: 22, text: "foresighted", meaning: "Öngörülü", category: "daily", type: "word" },
    { id: 23, text: "Sustainable", meaning: "Sürdürülebilir", category: "daily", type: "word" },
    { id: 24, text: "Context", meaning: "Bağlam", category: "daily", type: "word" },
    { id: 25, text: "Criteria", meaning: "Kriterler / Ölçütler", category: "daily", type: "word" },
    { id: 26, text: "Allocate", meaning: "Tahsis etmek", category: "daily", type: "word" },
    { id: 27, text: "Insight", meaning: "İçgörü", category: "daily", type: "word" },
    { id: 28, text: "Efficient", meaning: "Verimli", category: "daily", type: "word" },
    { id: 29, text: "Integrate", meaning: "Entegre etmek / Birleştirmek", category: "daily", type: "word" },
    { id: 30, text: "Consistency", meaning: "Tutarlılık / İstikrar", category: "daily", type: "word" },
    { id: 31, text: "Regularly", meaning: "Düzenli olarak", category: "daily", type: "word" },
    { id: 32, text: "Usually", meaning: "Genellikle", category: "daily", type: "word" },
    { id: 33, text: "Sometimes", meaning: "Bazen", category: "daily", type: "word" },
    { id: 34, text: "Often", meaning: "Sık sık", category: "daily", type: "word" },
    { id: 35, text: "Rarely", meaning: "Nadiren", category: "daily", type: "word" },
    { id: 36, text: "Morning", meaning: "Sabah", category: "daily", type: "word" },
    { id: 37, text: "Afternoon", meaning: "Öğleden sonra", category: "daily", type: "word" },
    { id: 38, text: "Evening", meaning: "Akşam", category: "daily", type: "word" },
    { id: 39, text: "Night", meaning: "Gece", category: "daily", type: "word" },
    { id: 40, text: "Today", meaning: "Bugün", category: "daily", type: "word" },
    { id: 41, text: "Tomorrow", meaning: "Yarın", category: "daily", type: "word" },
    { id: 42, text: "Yesterday", meaning: "Dün", category: "daily", type: "word" },
    { id: 43, text: "Always", meaning: "Her zaman", category: "daily", type: "word" },
    { id: 44, text: "Never", meaning: "Asla", category: "daily", type: "word" },,
    { id: 45, text: "Quickly", meaning: "Hızlıca", category: "daily", type: "word" },
    { id: 46, text: "Slowly", meaning: "Yavaşça", category: "daily", type: "word" },
    { id: 47, text: "Together", meaning: "Birlikte", category: "daily", type: "word" },
    { id: 48, text: "Alone", meaning: "Yalnız", category: "daily", type: "word" },
    { id: 49, text: "Again", meaning: "Tekrar", category: "daily", type: "word" },
    { id: 50, text: "Already", meaning: "Zaten", category: "daily", type: "word" },
    { id: 51, text: "I wake up early every day.", meaning: "Her gün erken kalkarım.", category: "daily", type: "sentence" },
    { id: 52, text: "I drink coffee in the morning.", meaning: "Sabahları kahve içerim.", category: "daily", type: "sentence" },
    { id: 53, text: "I go to school on weekdays.", meaning: "Hafta içi okula giderim.", category: "daily", type: "sentence" },
    { id: 54, text: "I study in the evening.", meaning: "Akşamları ders çalışırım.", category: "daily", type: "sentence" },
    { id: 55, text: "I check my phone frequently.", meaning: "Telefonumu sık sık kontrol ederim.", category: "daily", type: "sentence" },
    { id: 56, text: "I usually have breakfast at home.", meaning: "Genellikle evde kahvaltı yaparım.", category: "daily", type: "sentence" },
    { id: 57, text: "I listen to music while studying.", meaning: "Ders çalışırken müzik dinlerim.", category: "daily", type: "sentence" },
    { id: 58, text: "I walk to the bus stop.", meaning: "Otobüs durağına yürürüm.", category: "daily", type: "sentence" },
    { id: 59, text: "I arrive home in the evening.", meaning: "Akşam eve varırım.", category: "daily", type: "sentence" },
    { id: 60, text: "I eat dinner with my family.", meaning: "Ailemle akşam yemeği yerim.", category: "daily", type: "sentence" },
    { id: 61, text: "I watch videos before sleeping.", meaning: "Uyumadan önce video izlerim.", category: "daily", type: "sentence" },
    { id: 62, text: "I go to bed late sometimes.", meaning: "Bazen geç yatarım.", category: "daily", type: "sentence" },
    { id: 63, text: "I prepare my bag at night.", meaning: "Çantamı gece hazırlarım.", category: "daily", type: "sentence" },
    { id: 64, text: "I check my emails daily.", meaning: "E-postalarımı günlük kontrol ederim.", category: "daily", type: "sentence" },
    { id: 65, text: "I try to be productive.", meaning: "Verimli olmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 66, text: "I take short breaks while studying.", meaning: "Ders çalışırken kısa molalar veririm.", category: "daily", type: "sentence" },
    { id: 67, text: "I plan my day in advance.", meaning: "Günümü önceden planlarım.", category: "daily", type: "sentence" },
    { id: 68, text: "I spend time on my hobbies.", meaning: "Hobilerime zaman ayırırım.", category: "daily", type: "sentence" },
    { id: 69, text: "I try to sleep early.", meaning: "Erken uyumaya çalışırım.", category: "daily", type: "sentence" },
    { id: 70, text: "I review my notes.", meaning: "Notlarımı gözden geçiririm.", category: "daily", type: "sentence" },
    { id: 71, text: "I drink water regularly.", meaning: "Düzenli olarak su içerim.", category: "daily", type: "sentence" },
    { id: 72, text: "I focus better in the morning.", meaning: "Sabahları daha iyi odaklanırım.", category: "daily", type: "sentence" },
    { id: 73, text: "I finish my tasks on time.", meaning: "İşlerimi zamanında bitiririm.", category: "daily", type: "sentence" },
    { id: 74, text: "I relax after a long day.", meaning: "Uzun bir günün ardından rahatlarım.", category: "daily", type: "sentence" },
    { id: 75, text: "I get ready for the next day.", meaning: "Ertesi gün için hazırlanırım.", category: "daily", type: "sentence" },
    { id: 76, text: "Daily", meaning: "Günlük", category: "daily", type: "word" },
    { id: 77, text: "Routine", meaning: "Rutin", category: "daily", type: "word" },
    { id: 78, text: "Habit", meaning: "Alışkanlık", category: "daily", type: "word" },
    { id: 79, text: "Schedule", meaning: "Program", category: "daily", type: "word" },
    { id: 80, text: "Task", meaning: "Görev", category: "daily", type: "word" },
    { id: 81, text: "Break", meaning: "Mola", category: "daily", type: "word" },
    { id: 82, text: "Focus", meaning: "Odaklanmak", category: "daily", type: "word" },
    { id: 83, text: "Energy", meaning: "Enerji", category: "daily", type: "word" },
    { id: 84, text: "Busy", meaning: "Meşgul", category: "daily", type: "word" },
    { id: 85, text: "Free", meaning: "Boş / Özgür", category: "daily", type: "word" },
    { id: 86, text: "Early", meaning: "Erken", category: "daily", type: "word" },
    { id: 87, text: "Late", meaning: "Geç", category: "daily", type: "word" },
    { id: 88, text: "Healthy", meaning: "Sağlıklı", category: "daily", type: "word" },
    { id: 89, text: "Tired", meaning: "Yorgun", category: "daily", type: "word" },
    { id: 90, text: "Active", meaning: "Aktif", category: "daily", type: "word" },
    { id: 91, text: "Relax", meaning: "Rahatlamak", category: "daily", type: "word" },
    { id: 92, text: "Prepare", meaning: "Hazırlanmak", category: "daily", type: "word" },
    { id: 93, text: "Finish", meaning: "Bitirmek", category: "daily", type: "word" },
    { id: 94, text: "Start", meaning: "Başlamak", category: "daily", type: "word" },
    { id: 95, text: "Continue", meaning: "Devam etmek", category: "daily", type: "word" },
    { id: 96, text: "Improve", meaning: "Geliştirmek", category: "daily", type: "word" },
    { id: 97, text: "Repeat", meaning: "Tekrarlamak", category: "daily", type: "word" },
    { id: 98, text: "Rest", meaning: "Dinlenmek", category: "daily", type: "word" },
    { id: 99, text: "Balance", meaning: "Denge", category: "daily", type: "word" },
    { id: 100, text: "Goal", meaning: "Hedef", category: "daily", type: "word" },
    { id: 101, text: "I usually start my day with a plan.", meaning: "Genellikle güne bir planla başlarım.", category: "daily", type: "sentence" },
    { id: 102, text: "I try to manage my time efficiently.", meaning: "Zamanımı verimli yönetmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 103, text: "I feel more focused in a quiet place.", meaning: "Sessiz bir yerde daha iyi odaklanırım.", category: "daily", type: "sentence" },
    { id: 104, text: "I prefer studying in the morning.", meaning: "Sabah ders çalışmayı tercih ederim.", category: "daily", type: "sentence" },
    { id: 105, text: "I take notes to remember important things.", meaning: "Önemli şeyleri hatırlamak için not alırım.", category: "daily", type: "sentence" },
    { id: 106, text: "I try not to waste my time.", meaning: "Zamanımı boşa harcamamaya çalışırım.", category: "daily", type: "sentence" },
    { id: 107, text: "I feel tired when I sleep late.", meaning: "Geç uyuduğumda yorgun hissederim.", category: "daily", type: "sentence" },
    { id: 108, text: "I check my schedule every morning.", meaning: "Her sabah programımı kontrol ederim.", category: "daily", type: "sentence" },
    { id: 109, text: "I usually finish my tasks before dinner.", meaning: "Genellikle işlerimi akşam yemeğinden önce bitiririm.", category: "daily", type: "sentence" },
    { id: 110, text: "I try to stay organized during the day.", meaning: "Gün boyunca düzenli kalmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 111, text: "I feel relaxed after completing my work.", meaning: "İşlerimi bitirdikten sonra rahatlarım.", category: "daily", type: "sentence" },
    { id: 112, text: "I spend too much time on my phone sometimes.", meaning: "Bazen telefonumda çok fazla zaman geçiririm.", category: "daily", type: "sentence" },
    { id: 113, text: "I try to improve myself every day.", meaning: "Her gün kendimi geliştirmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 114, text: "I feel motivated when I reach my goals.", meaning: "Hedeflerime ulaştığımda motive olurum.", category: "daily", type: "sentence" },
    { id: 115, text: "I plan my tasks based on priority.", meaning: "Görevlerimi önceliğe göre planlarım.", category: "daily", type: "sentence" },
    { id: 116, text: "I prefer simple and clear instructions.", meaning: "Basit ve net talimatları tercih ederim.", category: "daily", type: "sentence" },
    { id: 117, text: "I try to stay calm in stressful situations.", meaning: "Stresli durumlarda sakin kalmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 118, text: "I feel productive when I follow a routine.", meaning: "Bir rutine uyduğumda kendimi verimli hissederim.", category: "daily", type: "sentence" },
    { id: 119, text: "I usually review my work at the end of the day.", meaning: "Genellikle gün sonunda yaptıklarımı gözden geçiririm.", category: "daily", type: "sentence" },
    { id: 120, text: "I try to balance work and rest.", meaning: "Çalışma ve dinlenme arasında denge kurmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 121, text: "I feel stressed when I am late.", meaning: "Geç kaldığımda stresli hissederim.", category: "daily", type: "sentence" },
    { id: 122, text: "I prepare everything before leaving home.", meaning: "Evden çıkmadan önce her şeyi hazırlarım.", category: "daily", type: "sentence" },
    { id: 123, text: "I feel better when I complete my plans.", meaning: "Planlarımı tamamladığımda daha iyi hissederim.", category: "daily", type: "sentence" },
    { id: 124, text: "I try to learn something new every day.", meaning: "Her gün yeni bir şey öğrenmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 125, text: "I usually solve problems step by step.", meaning: "Genellikle problemleri adım adım çözerim.", category: "daily", type: "sentence" },
    { id: 126, text: "I feel confident when I am well prepared.", meaning: "İyi hazırlandığımda kendime güvenirim.", category: "daily", type: "sentence" },
    { id: 127, text: "I try to avoid distractions while working.", meaning: "Çalışırken dikkat dağıtıcı şeylerden kaçınırım.", category: "daily", type: "sentence" },
    { id: 128, text: "I usually keep track of my progress.", meaning: "Genellikle ilerlememi takip ederim.", category: "daily", type: "sentence" },
    { id: 129, text: "I feel satisfied when I use my time well.", meaning: "Zamanımı iyi kullandığımda tatmin olurum.", category: "daily", type: "sentence" },
    { id: 130, text: "I organize my tasks to reduce stress.", meaning: "Stresi azaltmak için görevlerimi düzenlerim.", category: "daily", type: "sentence" },
    { id: 131, text: "I try to stay consistent with my habits.", meaning: "Alışkanlıklarımda tutarlı kalmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 132, text: "I usually feel tired after a long day.", meaning: "Uzun bir günün ardından genellikle yorgun hissederim.", category: "daily", type: "sentence" },
    { id: 133, text: "I try to finish important tasks first.", meaning: "Önemli görevleri önce bitirmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 134, text: "I feel more productive with a clear goal.", meaning: "Net bir hedefle daha verimli hissederim.", category: "daily", type: "sentence" },
    { id: 135, text: "I review my plans when something changes.", meaning: "Bir şey değiştiğinde planlarımı gözden geçiririm.", category: "daily", type: "sentence" },
    { id: 136, text: "I try to stay positive during the day.", meaning: "Gün boyunca pozitif kalmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 137, text: "I usually learn better by practicing.", meaning: "Genellikle pratik yaparak daha iyi öğrenirim.", category: "daily", type: "sentence" },
    { id: 138, text: "I feel motivated when I see progress.", meaning: "İlerleme gördüğümde motive olurum.", category: "daily", type: "sentence" },
    { id: 139, text: "I manage my daily tasks carefully.", meaning: "Günlük görevlerimi dikkatli yönetirim.", category: "daily", type: "sentence" },
    { id: 140, text: "I try to use my energy wisely.", meaning: "Enerjimi akıllıca kullanmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 141, text: "I feel more confident as I improve.", meaning: "Geliştikçe daha özgüvenli hissederim.", category: "daily", type: "sentence" },
    { id: 142, text: "I try to keep my life organized.", meaning: "Hayatımı düzenli tutmaya çalışırım.", category: "daily", type: "sentence" },
    { id: 143, text: "I usually prepare a to-do list.", meaning: "Genellikle yapılacaklar listesi hazırlarım.", category: "daily", type: "sentence" },
    { id: 144, text: "I feel better when I follow my plan.", meaning: "Planıma uyduğumda kendimi daha iyi hissederim.", category: "daily", type: "sentence" },
    { id: 145, text: "I try to finish what I start.", meaning: "Başladığım işi bitirmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 146, text: "I usually reflect on my day at night.", meaning: "Genellikle gece günümü değerlendiririm.", category: "daily", type: "sentence" },
    { id: 147, text: "I feel proud when I achieve my goals.", meaning: "Hedeflerime ulaştığımda gurur duyarım.", category: "daily", type: "sentence" },
    { id: 148, text: "I try to improve my routine over time.", meaning: "Zamanla rutinimi geliştirmeye çalışırım.", category: "daily", type: "sentence" },
    { id: 149, text: "I manage my responsibilities carefully.", meaning: "Sorumluluklarımı dikkatle yönetirim.", category: "daily", type: "sentence" },
    { id: 150, text: "I believe consistency brings success.", meaning: "Tutarlılığın başarı getirdiğine inanırım.", category: "daily", type: "sentence" },
    { id: 151, text: "Linear Polarization", meaning: "Doğrusal Polarizasyon", category: "technical", type: "word" },
    { id: 152, text: "Antenna Gain", meaning: "Anten Kazancı", category: "technical", type: "word" },
    { id: 153, text: "Radiation Pattern", meaning: "Işıma Diyagramı", category: "technical", type: "word" },
    { id: 154, text: "Beamwidth", meaning: "Işın Genişliği", category: "technical", type: "word" },
    { id: 155, text: "Side Lobe", meaning: "Yan Lob", category: "technical", type: "word" },
    { id: 156, text: "Main Lobe", meaning: "Ana Lob", category: "technical", type: "word" },
    { id: 157, text: "Return Loss", meaning: "Geri Dönüş Kaybı", category: "technical", type: "word" },
    { id: 158, text: "Insertion Loss", meaning: "Ekleme Kaybı", category: "technical", type: "word" },
    { id: 159, text: "VSWR", meaning: "Gerilim Duran Dalga Oranı", category: "technical", type: "word" },
    { id: 160, text: "Impedance Matching", meaning: "Empedans Eşleştirme", category: "technical", type: "word" },
    { id: 161, text: "Bandwidth", meaning: "Bant Genişliği", category: "technical", type: "word" },
    { id: 162, text: "Center Frequency", meaning: "Merkez Frekans", category: "technical", type: "word" },
    { id: 163, text: "Resonant Frequency", meaning: "Rezonans Frekansı", category: "technical", type: "word" },
    { id: 164, text: "Electromagnetic Wave", meaning: "Elektromanyetik Dalga", category: "technical", type: "word" },
    { id: 165, text: "Free Space", meaning: "Serbest Uzay", category: "technical", type: "word" },
    { id: 166, text: "Far Field", meaning: "Uzak Alan", category: "technical", type: "word" },
    { id: 167, text: "Near Field", meaning: "Yakın Alan", category: "technical", type: "word" },
    { id: 168, text: "Ground Plane", meaning: "Toprak Düzlemi", category: "technical", type: "word" },
    { id: 169, text: "Microstrip Line", meaning: "Mikroşerit Hat", category: "technical", type: "word" },
    { id: 170, text: "Patch Antenna", meaning: "Yama Anten", category: "technical", type: "word" },
    { id: 171, text: "Array Antenna", meaning: "Dizi Anten", category: "technical", type: "word" },
    { id: 172, text: "Phase Shift", meaning: "Faz Kayması", category: "technical", type: "word" },
    { id: 173, text: "Beamforming", meaning: "Işın Oluşturma", category: "technical", type: "word" },
    { id: 174, text: "Signal-to-Noise Ratio", meaning: "Sinyal-Gürültü Oranı", category: "technical", type: "word" },
    { id: 175, text: "Noise Figure", meaning: "Gürültü Katsayısı", category: "technical", type: "word" },
    { id: 176, text: "Low Noise Amplifier", meaning: "Düşük Gürültülü Yükselteç", category: "technical", type: "word" },
    { id: 177, text: "Band Pass Filter", meaning: "Bant Geçiren Filtre", category: "technical", type: "word" },
    { id: 178, text: "Frequency Response", meaning: "Frekans Tepkisi", category: "technical", type: "word" },
    { id: 179, text: "Attenuation", meaning: "Zayıflama", category: "technical", type: "word" },
    { id: 180, text: "Reflection Coefficient", meaning: "Yansıma Katsayısı", category: "technical", type: "word" },
    { id: 181, text: "Propagation", meaning: "Yayılım", category: "technical", type: "word" },
    { id: 182, text: "Path Loss", meaning: "Yol Kaybı", category: "technical", type: "word" },
    { id: 183, text: "Line of Sight", meaning: "Görüş Hattı", category: "technical", type: "word" },
    { id: 184, text: "Multipath", meaning: "Çok Yollu Yayılım", category: "technical", type: "word" },
    { id: 185, text: "Interference", meaning: "Girişim", category: "technical", type: "word" },
    { id: 186, text: "Jamming", meaning: "Karıştırma", category: "technical", type: "word" },
    { id: 187, text: "Spoofing", meaning: "Aldatıcı Sinyal Üretimi", category: "technical", type: "word" },
    { id: 188, text: "Carrier Frequency", meaning: "Taşıyıcı Frekans", category: "technical", type: "word" },
    { id: 189, text: "Modulation", meaning: "Modülasyon", category: "technical", type: "word" },
    { id: 190, text: "Demodulation", meaning: "Demodülasyon", category: "technical", type: "word" },
    { id: 191, text: "Phase Noise", meaning: "Faz Gürültüsü", category: "technical", type: "word" },
    { id: 192, text: "Clock Drift", meaning: "Saat Kayması", category: "technical", type: "word" },
    { id: 193, text: "Synchronization", meaning: "Senkronizasyon", category: "technical", type: "word" },
    { id: 194, text: "Sampling Rate", meaning: "Örnekleme Frekansı", category: "technical", type: "word" },
    { id: 195, text: "Quantization", meaning: "Nicemleme", category: "technical", type: "word" },
    { id: 196, text: "Digital Signal Processing", meaning: "Sayısal Sinyal İşleme", category: "technical", type: "word" },
    { id: 197, text: "Analog Signal", meaning: "Analog Sinyal", category: "technical", type: "word" },
    { id: 198, text: "Digital Signal", meaning: "Sayısal Sinyal", category: "technical", type: "word" },
    { id: 199, text: "Transmission Line", meaning: "İletim Hattı", category: "technical", type: "word" },
    { id: 200, text: "Electromagnetic Compatibility", meaning: "Elektromanyetik Uyumluluk", category: "technical", type: "word" },
    { id: 201, text: "Engineering", meaning: "Mühendislik", category: "technical", type: "word" },
    { id: 202, text: "Design", meaning: "Tasarım", category: "technical", type: "word" },
    { id: 203, text: "Analysis", meaning: "Analiz", category: "technical", type: "word" },
    { id: 204, text: "System", meaning: "Sistem", category: "technical", type: "word" },
    { id: 205, text: "Component", meaning: "Bileşen", category: "technical", type: "word" },
    { id: 206, text: "Process", meaning: "Süreç", category: "technical", type: "word" },
    { id: 207, text: "Model", meaning: "Model", category: "technical", type: "word" },
    { id: 208, text: "Simulation", meaning: "Simülasyon", category: "technical", type: "word" },
    { id: 209, text: "Prototype", meaning: "Prototip", category: "technical", type: "word" },
    { id: 210, text: "Testing", meaning: "Test", category: "technical", type: "word" },
    { id: 211, text: "Development", meaning: "Geliştirme", category: "technical", type: "word" },
    { id: 212, text: "Implementation", meaning: "Uygulama", category: "technical", type: "word" },
    { id: 213, text: "Optimization", meaning: "Optimizasyon", category: "technical", type: "word" },
    { id: 214, text: "Efficiency", meaning: "Verimlilik", category: "technical", type: "word" },
    { id: 215, text: "Performance", meaning: "Performans", category: "technical", type: "word" },
    { id: 216, text: "Accuracy", meaning: "Doğruluk", category: "technical", type: "word" },
    { id: 217, text: "Precision", meaning: "Hassasiyet", category: "technical", type: "word" },
    { id: 218, text: "Reliability", meaning: "Güvenilirlik", category: "technical", type: "word" },
    { id: 219, text: "Durability", meaning: "Dayanıklılık", category: "technical", type: "word" },
    { id: 220, text: "Safety", meaning: "Güvenlik", category: "technical", type: "word" },
    { id: 221, text: "Standard", meaning: "Standart", category: "technical", type: "word" },
    { id: 222, text: "Specification", meaning: "Teknik Şartname", category: "technical", type: "word" },
    { id: 223, text: "Requirement", meaning: "Gereksinim", category: "technical", type: "word" },
    { id: 224, text: "Constraint", meaning: "Kısıt", category: "technical", type: "word" },
    { id: 225, text: "Tolerance", meaning: "Tolerans", category: "technical", type: "word" },
    { id: 226, text: "Measurement", meaning: "Ölçüm", category: "technical", type: "word" },
    { id: 227, text: "Calibration", meaning: "Kalibrasyon", category: "technical", type: "word" },
    { id: 228, text: "Validation", meaning: "Doğrulama", category: "technical", type: "word" },
    { id: 229, text: "Verification", meaning: "Teyit", category: "technical", type: "word" },
    { id: 230, text: "Inspection", meaning: "Denetim", category: "technical", type: "word" },
    { id: 231, text: "Manufacturing", meaning: "Üretim", category: "technical", type: "word" },
    { id: 232, text: "Assembly", meaning: "Montaj", category: "technical", type: "word" },
    { id: 233, text: "Integration", meaning: "Entegrasyon", category: "technical", type: "word" },
    { id: 234, text: "Maintenance", meaning: "Bakım", category: "technical", type: "word" },
    { id: 235, text: "Operation", meaning: "İşletim", category: "technical", type: "word" },
    { id: 236, text: "Failure", meaning: "Arıza / Hata", category: "technical", type: "word" },
    { id: 237, text: "Fault", meaning: "Kusur", category: "technical", type: "word" },
    { id: 238, text: "Troubleshooting", meaning: "Arıza Giderme", category: "technical", type: "word" },
    { id: 239, text: "Risk", meaning: "Risk", category: "technical", type: "word" },
    { id: 240, text: "Assessment", meaning: "Değerlendirme", category: "technical", type: "word" },
    { id: 241, text: "Project", meaning: "Proje", category: "technical", type: "word" },
    { id: 242, text: "Planning", meaning: "Planlama", category: "technical", type: "word" },
    { id: 243, text: "Scheduling", meaning: "Zamanlama", category: "technical", type: "word" },
    { id: 244, text: "Deadline", meaning: "Son teslim tarihi", category: "technical", type: "word" },
    { id: 245, text: "Milestone", meaning: "Kilometre taşı", category: "technical", type: "word" },
    { id: 246, text: "Budget", meaning: "Bütçe", category: "technical", type: "word" },
    { id: 247, text: "Cost", meaning: "Maliyet", category: "technical", type: "word" },
    { id: 248, text: "Resource", meaning: "Kaynak", category: "technical", type: "word" },
    { id: 249, text: "Productivity", meaning: "Üretkenlik", category: "technical", type: "word" },
    { id: 250, text: "Workflow", meaning: "İş Akışı", category: "technical", type: "word" },
    { id: 251, text: "Documentation", meaning: "Dokümantasyon", category: "technical", type: "word" },
    { id: 252, text: "Report", meaning: "Rapor", category: "technical", type: "word" },
    { id: 253, text: "Presentation", meaning: "Sunum", category: "technical", type: "word" },
    { id: 254, text: "Technical Drawing", meaning: "Teknik Çizim", category: "technical", type: "word" },
    { id: 255, text: "Diagram", meaning: "Diyagram", category: "technical", type: "word" },
    { id: 256, text: "Algorithm", meaning: "Algoritma", category: "technical", type: "word" },
    { id: 257, text: "Logic", meaning: "Mantık", category: "technical", type: "word" },
    { id: 258, text: "Automation", meaning: "Otomasyon", category: "technical", type: "word" },
    { id: 259, text: "Control", meaning: "Kontrol", category: "technical", type: "word" },
    { id: 260, text: "Monitoring", meaning: "İzleme", category: "technical", type: "word" },
    { id: 261, text: "Data", meaning: "Veri", category: "technical", type: "word" },
    { id: 262, text: "Database", meaning: "Veritabanı", category: "technical", type: "word" },
    { id: 263, text: "Interface", meaning: "Arayüz", category: "technical", type: "word" },
    { id: 264, text: "Compatibility", meaning: "Uyumluluk", category: "technical", type: "word" },
    { id: 265, text: "Scalability", meaning: "Ölçeklenebilirlik", category: "technical", type: "word" },
    { id: 266, text: "Innovation", meaning: "Yenilik", category: "technical", type: "word" },
    { id: 267, text: "Improvement", meaning: "İyileştirme", category: "technical", type: "word" },
    { id: 268, text: "Sustainability", meaning: "Sürdürülebilirlik", category: "technical", type: "word" },
    { id: 269, text: "Feasibility", meaning: "Yapılabilirlik", category: "technical", type: "word" },
    { id: 270, text: "Solution", meaning: "Çözüm", category: "technical", type: "word" },
    { id: 271, text: "Problem Solving", meaning: "Problem Çözme", category: "technical", type: "word" },
    { id: 272, text: "Critical Thinking", meaning: "Eleştirel Düşünme", category: "technical", type: "word" },
    { id: 273, text: "Decision Making", meaning: "Karar Verme", category: "technical", type: "word" },
    { id: 274, text: "Collaboration", meaning: "İş Birliği", category: "technical", type: "word" },
    { id: 275, text: "Teamwork", meaning: "Takım Çalışması", category: "technical", type: "word" },
    { id: 276, text: "Leadership", meaning: "Liderlik", category: "technical", type: "word" },
    { id: 277, text: "Responsibility", meaning: "Sorumluluk", category: "technical", type: "word" },
    { id: 278, text: "Ethics", meaning: "Etik", category: "technical", type: "word" },
    { id: 279, text: "Quality", meaning: "Kalite", category: "technical", type: "word" },
    { id: 280, text: "Assurance", meaning: "Güvence", category: "technical", type: "word" },
    { id: 281, text: "Constraint Analysis", meaning: "Kısıt Analizi", category: "technical", type: "word" },
    { id: 282, text: "System Architecture", meaning: "Sistem Mimarisi", category: "technical", type: "word" },
    { id: 283, text: "Design Review", meaning: "Tasarım Gözden Geçirme", category: "technical", type: "word" },
    { id: 284, text: "Root Cause", meaning: "Kök Neden", category: "technical", type: "word" },
    { id: 285, text: "Iteration", meaning: "Yineleme", category: "technical", type: "word" },
    { id: 286, text: "Trade-off", meaning: "Ödünleşim", category: "technical", type: "word" },
    { id: 287, text: "Benchmark", meaning: "Kıyaslama", category: "technical", type: "word" },
    { id: 288, text: "Lifecycle", meaning: "Yaşam Döngüsü", category: "technical", type: "word" },
    { id: 289, text: "Deployment", meaning: "Devreye Alma", category: "technical", type: "word" },
    { id: 290, text: "Upgrade", meaning: "Yükseltme", category: "technical", type: "word" },
    { id: 291, text: "Configuration", meaning: "Yapılandırma", category: "technical", type: "word" },
    { id: 292, text: "Version Control", meaning: "Sürüm Kontrolü", category: "technical", type: "word" },
    { id: 293, text: "Debugging", meaning: "Hata Ayıklama", category: "technical", type: "word" },
    { id: 294, text: "Interface Design", meaning: "Arayüz Tasarımı", category: "technical", type: "word" },
    { id: 295, text: "System Integration", meaning: "Sistem Entegrasyonu", category: "technical", type: "word" },
    { id: 296, text: "Compliance", meaning: "Uygunluk", category: "technical", type: "word" },
    { id: 297, text: "Certification", meaning: "Sertifikasyon", category: "technical", type: "word" },
    { id: 298, text: "Documentation Control", meaning: "Doküman Kontrolü", category: "technical", type: "word" },
    { id: 299, text: "Knowledge Transfer", meaning: "Bilgi Aktarımı", category: "technical", type: "word" },
    { id: 300, text: "Continuous Improvement", meaning: "Sürekli İyileştirme", category: "technical", type: "word" },
    { id: 301, text: "However", meaning: "Ancak", category: "daily", type: "word" },
    { id: 302, text: "Therefore", meaning: "Bu nedenle", category: "daily", type: "word" },
    { id: 303, text: "Moreover", meaning: "Ayrıca", category: "daily", type: "word" },
    { id: 304, text: "Although", meaning: "Her ne kadar", category: "daily", type: "word" },
    { id: 305, text: "Despite", meaning: "-e rağmen", category: "daily", type: "word" },
    { id: 306, text: "Whereas", meaning: "Oysa ki", category: "daily", type: "word" },
    { id: 307, text: "Thus", meaning: "Böylece", category: "daily", type: "word" },
    { id: 308, text: "Hence", meaning: "Dolayısıyla", category: "daily", type: "word" },
    { id: 309, text: "Nevertheless", meaning: "Buna rağmen", category: "daily", type: "word" },
    { id: 310, text: "Otherwise", meaning: "Aksi takdirde", category: "daily", type: "word" },
    { id: 311, text: "Meanwhile", meaning: "Bu sırada", category: "daily", type: "word" },
    { id: 312, text: "Furthermore", meaning: "Dahası", category: "daily", type: "word" },
    { id: 313, text: "Likewise", meaning: "Benzer şekilde", category: "daily", type: "word" },
    { id: 314, text: "Instead", meaning: "Bunun yerine", category: "daily", type: "word" },
    { id: 315, text: "Rather", meaning: "Daha doğrusu", category: "daily", type: "word" },
    { id: 316, text: "Accordingly", meaning: "Buna bağlı olarak", category: "daily", type: "word" },
    { id: 317, text: "Nonetheless", meaning: "Yine de", category: "daily", type: "word" },
    { id: 318, text: "Henceforth", meaning: "Bundan böyle", category: "daily", type: "word" },
    { id: 319, text: "Thereby", meaning: "Bu yolla", category: "daily", type: "word" },
    { id: 320, text: "Otherwise", meaning: "Aksi halde", category: "daily", type: "word" },
    { id: 321, text: "Regardless", meaning: "-e bakmaksızın", category: "daily", type: "word" },
    { id: 322, text: "Albeit", meaning: "Her ne kadar", category: "daily", type: "word" },
    { id: 323, text: "Notwithstanding", meaning: "-e rağmen", category: "daily", type: "word" },
    { id: 324, text: "Thereafter", meaning: "Ondan sonra", category: "daily", type: "word" },
    { id: 325, text: "Therein", meaning: "Bunun içinde", category: "daily", type: "word" },
    { id: 326, text: "Meanwhile", meaning: "Bu esnada", category: "daily", type: "word" },
    { id: 327, text: "Subsequently", meaning: "Sonrasında", category: "daily", type: "word" },
    { id: 328, text: "Previously", meaning: "Önceden", category: "daily", type: "word" },
    { id: 329, text: "Eventually", meaning: "Eninde sonunda", category: "daily", type: "word" },
    { id: 330, text: "Consequently", meaning: "Sonuç olarak", category: "daily", type: "word" },
    { id: 331, text: "Instead of", meaning: "Yerine", category: "daily", type: "word" },
    { id: 332, text: "As long as", meaning: "-dığı sürece", category: "daily", type: "word" },
    { id: 333, text: "In contrast", meaning: "Buna karşılık", category: "daily", type: "word" },
    { id: 334, text: "In addition", meaning: "Ek olarak", category: "daily", type: "word" },
    { id: 335, text: "As a result", meaning: "Sonuç olarak", category: "daily", type: "word" },
    { id: 336, text: "As a whole", meaning: "Genel olarak", category: "daily", type: "word" },
    { id: 337, text: "At least", meaning: "En azından", category: "daily", type: "word" },
    { id: 338, text: "At most", meaning: "En fazla", category: "daily", type: "word" },
    { id: 339, text: "So far", meaning: "Şimdiye kadar", category: "daily", type: "word" },
    { id: 340, text: "In advance", meaning: "Önceden", category: "daily", type: "word" },
    { id: 341, text: "On the other hand", meaning: "Öte yandan", category: "daily", type: "word" },
    { id: 342, text: "By contrast", meaning: "Buna karşın", category: "daily", type: "word" },
    { id: 343, text: "Even though", meaning: "Her ne kadar", category: "daily", type: "word" },
    { id: 344, text: "As soon as", meaning: "-er ermez", category: "daily", type: "word" },
    { id: 345, text: "Provided that", meaning: "Şartıyla", category: "daily", type: "word" },
    { id: 346, text: "In the meantime", meaning: "Bu arada", category: "daily", type: "word" },
    { id: 347, text: "All of a sudden", meaning: "Aniden", category: "daily", type: "word" },
    { id: 348, text: "From time to time", meaning: "Zaman zaman", category: "daily", type: "word" },
    { id: 349, text: "In general", meaning: "Genel olarak", category: "daily", type: "word" },
    { id: 350, text: "By no means", meaning: "Asla", category: "daily", type: "word" },
    { id: 351, text: "Indicate", meaning: "Göstermek", category: "technical", type: "word" },
    { id: 352, text: "Demonstrate", meaning: "Ortaya koymak", category: "technical", type: "word" },
    { id: 353, text: "Reveal", meaning: "Açığa çıkarmak", category: "technical", type: "word" },
    { id: 354, text: "Suggest", meaning: "Öne sürmek", category: "technical", type: "word" },
    { id: 355, text: "Assume", meaning: "Varsaymak", category: "technical", type: "word" },
    { id: 356, text: "Claim", meaning: "İddia etmek", category: "technical", type: "word" },
    { id: 357, text: "Maintain", meaning: "Savunmak / sürdürmek", category: "technical", type: "word" },
    { id: 358, text: "Contribute", meaning: "Katkıda bulunmak", category: "technical", type: "word" },
    { id: 359, text: "Affect", meaning: "Etkilemek", category: "technical", type: "word" },
    { id: 360, text: "Enable", meaning: "Olanak sağlamak", category: "technical", type: "word" },
    { id: 361, text: "Require", meaning: "Gerektirmek", category: "technical", type: "word" },
    { id: 362, text: "Establish", meaning: "Ortaya koymak", category: "technical", type: "word" },
    { id: 363, text: "Determine", meaning: "Belirlemek", category: "technical", type: "word" },
    { id: 364, text: "Enhance", meaning: "Artırmak", category: "technical", type: "word" },
    { id: 365, text: "Limit", meaning: "Sınırlandırmak", category: "technical", type: "word" },
    { id: 366, text: "Evidence", meaning: "Kanıt", category: "technical", type: "word" },
    { id: 367, text: "Approach", meaning: "Yaklaşım", category: "technical", type: "word" },
    { id: 368, text: "Outcome", meaning: "Sonuç", category: "technical", type: "word" },
    { id: 369, text: "Impact", meaning: "Etki", category: "technical", type: "word" },
    { id: 370, text: "Factor", meaning: "Etken", category: "technical", type: "word" },
    { id: 371, text: "Aspect", meaning: "Yön", category: "technical", type: "word" },
    { id: 372, text: "Context", meaning: "Bağlam", category: "technical", type: "word" },
    { id: 373, text: "Assumption", meaning: "Varsayım", category: "technical", type: "word" },
    { id: 374, text: "Conclusion", meaning: "Sonuç", category: "technical", type: "word" },
    { id: 375, text: "Scope", meaning: "Kapsam", category: "technical", type: "word" },
    { id: 376, text: "Significant", meaning: "Önemli", category: "technical", type: "word" },
    { id: 377, text: "Relevant", meaning: "İlgili", category: "technical", type: "word" },
    { id: 378, text: "Adequate", meaning: "Yeterli", category: "technical", type: "word" },
    { id: 379, text: "Essential", meaning: "Gerekli", category: "technical", type: "word" },
    { id: 380, text: "Consistent", meaning: "Tutarlı", category: "technical", type: "word" },
    { id: 381, text: "Phenomenon", meaning: "Olgu", category: "technical", type: "word" },
    { id: 382, text: "Hypothesis", meaning: "Hipotez", category: "technical", type: "word" },
    { id: 383, text: "Correlation", meaning: "Korelasyon", category: "technical", type: "word" },
    { id: 384, text: "Implication", meaning: "Çıkarım", category: "technical", type: "word" },
    { id: 385, text: "Framework", meaning: "Çerçeve", category: "technical", type: "word" },
    { id: 386, text: "Underlying", meaning: "Altta yatan", category: "technical", type: "word" },
    { id: 387, text: "Validity", meaning: "Geçerlilik", category: "technical", type: "word" },
    { id: 388, text: "Reliability", meaning: "Güvenilirlik", category: "technical", type: "word" },
    { id: 389, text: "Inference", meaning: "Çıkarım", category: "technical", type: "word" },
    { id: 390, text: "Constraint", meaning: "Kısıt", category: "technical", type: "word" },
    { id: 391, text: "Subsequent", meaning: "Sonraki", category: "technical", type: "word" },
    { id: 392, text: "Preceding", meaning: "Önceki", category: "technical", type: "word" },
    { id: 393, text: "Likely", meaning: "Olası", category: "technical", type: "word" },
    { id: 394, text: "Potential", meaning: "Potansiyel", category: "technical", type: "word" },
    { id: 395, text: "Complex", meaning: "Karmaşık", category: "technical", type: "word" },
    { id: 396, text: "Method", meaning: "Yöntem", category: "technical", type: "word" },
    { id: 397, text: "Data", meaning: "Veri", category: "technical", type: "word" },
    { id: 398, text: "Process", meaning: "Süreç", category: "technical", type: "word" },
    { id: 399, text: "Trend", meaning: "Eğilim", category: "technical", type: "word" },
    { id: 400, text: "Purpose", meaning: "Amaç", category: "technical", type: "word" },
    { id: 401, text: "The system was designed to improve overall performance.", meaning: "Sistem, genel performansı artırmak için tasarlandı.", category: "technical", type: "sentence" },
    { id: 402, text: "This method is widely used in engineering applications.", meaning: "Bu yöntem mühendislik uygulamalarında yaygın olarak kullanılır.", category: "technical", type: "sentence" },
    { id: 403, text: "The results indicate a significant improvement.", meaning: "Sonuçlar önemli bir iyileşmeye işaret etmektedir.", category: "technical", type: "sentence" },
    { id: 404, text: "The experiment was conducted under controlled conditions.", meaning: "Deney kontrollü koşullar altında gerçekleştirildi.", category: "technical", type: "sentence" },
    { id: 405, text: "The data were analyzed using statistical methods.", meaning: "Veriler istatistiksel yöntemler kullanılarak analiz edildi.", category: "technical", type: "sentence" },
    { id: 406, text: "This approach reduces the overall system cost.", meaning: "Bu yaklaşım toplam sistem maliyetini azaltır.", category: "technical", type: "sentence" },
    { id: 407, text: "The proposed solution meets the required standards.", meaning: "Önerilen çözüm gerekli standartları karşılamaktadır.", category: "technical", type: "sentence" },
    { id: 408, text: "The model was validated through multiple tests.", meaning: "Model birden fazla test ile doğrulandı.", category: "technical", type: "sentence" },
    { id: 409, text: "System reliability is a critical factor.", meaning: "Sistem güvenilirliği kritik bir faktördür.", category: "technical", type: "sentence" },
    { id: 410, text: "The design process includes several stages.", meaning: "Tasarım süreci birkaç aşamadan oluşur.", category: "technical", type: "sentence" },
    { id: 411, text: "The performance depends on various parameters.", meaning: "Performans çeşitli parametrelere bağlıdır.", category: "technical", type: "sentence" },
    { id: 412, text: "The algorithm improves processing efficiency.", meaning: "Algoritma işlem verimliliğini artırır.", category: "technical", type: "sentence" },
    { id: 413, text: "The system operates within defined limits.", meaning: "Sistem tanımlı sınırlar içinde çalışır.", category: "technical", type: "sentence" },
    { id: 414, text: "This technique minimizes energy consumption.", meaning: "Bu teknik enerji tüketimini en aza indirir.", category: "technical", type: "sentence" },
    { id: 415, text: "The experiment confirmed the initial hypothesis.", meaning: "Deney başlangıç hipotezini doğruladı.", category: "technical", type: "sentence" },
    { id: 416, text: "The process was optimized for better efficiency.", meaning: "Süreç daha iyi verimlilik için optimize edildi.", category: "technical", type: "sentence" },
    { id: 417, text: "The results were consistent with previous studies.", meaning: "Sonuçlar önceki çalışmalarla tutarlıydı.", category: "technical", type: "sentence" },
    { id: 418, text: "The system requires regular maintenance.", meaning: "Sistem düzenli bakım gerektirir.", category: "technical", type: "sentence" },
    { id: 419, text: "The analysis focuses on key performance metrics.", meaning: "Analiz temel performans metriklerine odaklanır.", category: "technical", type: "sentence" },
    { id: 420, text: "The device was tested under real-world conditions.", meaning: "Cihaz gerçek dünya koşullarında test edildi.", category: "technical", type: "sentence" },
    { id: 421, text: "The method provides reliable results.", meaning: "Yöntem güvenilir sonuçlar sağlar.", category: "technical", type: "sentence" },
    { id: 422, text: "The system architecture supports scalability.", meaning: "Sistem mimarisi ölçeklenebilirliği destekler.", category: "technical", type: "sentence" },
    { id: 423, text: "The experiment aims to evaluate system behavior.", meaning: "Deney sistem davranışını değerlendirmeyi amaçlar.", category: "technical", type: "sentence" },
    { id: 424, text: "The solution was implemented successfully.", meaning: "Çözüm başarıyla uygulandı.", category: "technical", type: "sentence" },
    { id: 425, text: "The data suggest a strong correlation.", meaning: "Veriler güçlü bir korelasyon olduğunu göstermektedir.", category: "technical", type: "sentence" },
    { id: 426, text: "The system must comply with safety regulations.", meaning: "Sistem güvenlik yönetmeliklerine uymalıdır.", category: "technical", type: "sentence" },
    { id: 427, text: "The design was revised based on feedback.", meaning: "Tasarım geri bildirimlere göre revize edildi.", category: "technical", type: "sentence" },
    { id: 428, text: "The experiment highlights potential limitations.", meaning: "Deney potansiyel sınırlamaları ortaya koymaktadır.", category: "technical", type: "sentence" },
    { id: 429, text: "The process ensures consistent quality.", meaning: "Süreç tutarlı kaliteyi garanti eder.", category: "technical", type: "sentence" },
    { id: 430, text: "The system integrates multiple components.", meaning: "Sistem birden fazla bileşeni entegre eder.", category: "technical", type: "sentence" },
    { id: 431, text: "The results were obtained through careful analysis.", meaning: "Sonuçlar dikkatli bir analizle elde edildi.", category: "technical", type: "sentence" },
    { id: 432, text: "The approach enhances overall system stability.", meaning: "Yaklaşım genel sistem kararlılığını artırır.", category: "technical", type: "sentence" },
    { id: 433, text: "The system performance was evaluated thoroughly.", meaning: "Sistem performansı ayrıntılı şekilde değerlendirildi.", category: "technical", type: "sentence" },
    { id: 434, text: "The method reduces operational complexity.", meaning: "Yöntem operasyonel karmaşıklığı azaltır.", category: "technical", type: "sentence" },
    { id: 435, text: "The experiment produced repeatable results.", meaning: "Deney tekrarlanabilir sonuçlar üretti.", category: "technical", type: "sentence" },
    { id: 436, text: "The system was developed using modern tools.", meaning: "Sistem modern araçlar kullanılarak geliştirildi.", category: "technical", type: "sentence" },
    { id: 437, text: "The design meets functional requirements.", meaning: "Tasarım işlevsel gereksinimleri karşılar.", category: "technical", type: "sentence" },
    { id: 438, text: "The analysis considers multiple variables.", meaning: "Analiz birden fazla değişkeni dikkate alır.", category: "technical", type: "sentence" },
    { id: 439, text: "The solution improves system reliability.", meaning: "Çözüm sistem güvenilirliğini artırır.", category: "technical", type: "sentence" },
    { id: 440, text: "The experiment supports the proposed model.", meaning: "Deney önerilen modeli desteklemektedir.", category: "technical", type: "sentence" },
    { id: 441, text: "The system performance varies with conditions.", meaning: "Sistem performansı koşullara göre değişir.", category: "technical", type: "sentence" },
    { id: 442, text: "The process was designed to minimize errors.", meaning: "Süreç hataları en aza indirecek şekilde tasarlandı.", category: "technical", type: "sentence" },
    { id: 443, text: "The data were collected over a long period.", meaning: "Veriler uzun bir süre boyunca toplandı.", category: "technical", type: "sentence" },
    { id: 444, text: "The system ensures efficient resource usage.", meaning: "Sistem kaynakların verimli kullanımını sağlar.", category: "technical", type: "sentence" },
    { id: 445, text: "The results highlight key performance trends.", meaning: "Sonuçlar temel performans eğilimlerini vurgular.", category: "technical", type: "sentence" },
    { id: 446, text: "The design improves operational efficiency.", meaning: "Tasarım operasyonel verimliliği artırır.", category: "technical", type: "sentence" },
    { id: 447, text: "The experiment reveals important insights.", meaning: "Deney önemli çıkarımlar ortaya koymaktadır.", category: "technical", type: "sentence" },
    { id: 448, text: "The system configuration affects performance.", meaning: "Sistem yapılandırması performansı etkiler.", category: "technical", type: "sentence" },
    { id: 449, text: "The method was chosen for its simplicity.", meaning: "Yöntem sadeliği nedeniyle seçildi.", category: "technical", type: "sentence" },
    { id: 450, text: "The results are relevant to practical applications.", meaning: "Sonuçlar pratik uygulamalar için önemlidir.", category: "technical", type: "sentence" },
    { id: 451, text: "The system supports continuous operation.", meaning: "Sistem sürekli çalışmayı destekler.", category: "technical", type: "sentence" },
    { id: 452, text: "The analysis identifies key problem areas.", meaning: "Analiz temel problem alanlarını belirler.", category: "technical", type: "sentence" },
    { id: 453, text: "The experiment was repeated for accuracy.", meaning: "Deney doğruluk için tekrarlandı.", category: "technical", type: "sentence" },
    { id: 454, text: "The design process requires careful planning.", meaning: "Tasarım süreci dikkatli planlama gerektirir.", category: "technical", type: "sentence" },
    { id: 455, text: "The system achieves high performance levels.", meaning: "Sistem yüksek performans seviyelerine ulaşır.", category: "technical", type: "sentence" },
    { id: 456, text: "The solution reduces overall system complexity.", meaning: "Çözüm genel sistem karmaşıklığını azaltır.", category: "technical", type: "sentence" },
    { id: 457, text: "The experiment confirms system stability.", meaning: "Deney sistem kararlılığını doğrular.", category: "technical", type: "sentence" },
    { id: 458, text: "The method ensures accurate measurements.", meaning: "Yöntem doğru ölçümler sağlar.", category: "technical", type: "sentence" },
    { id: 459, text: "The system design follows industry standards.", meaning: "Sistem tasarımı endüstri standartlarını takip eder.", category: "technical", type: "sentence" },
    { id: 460, text: "The results contribute to future research.", meaning: "Sonuçlar gelecekteki araştırmalara katkı sağlar.", category: "technical", type: "sentence" },
    { id: 461, text: "The system was optimized for long-term use.", meaning: "Sistem uzun vadeli kullanım için optimize edildi.", category: "technical", type: "sentence" },
    { id: 462, text: "The experiment demonstrates method effectiveness.", meaning: "Deney yöntemin etkinliğini göstermektedir.", category: "technical", type: "sentence" },
    { id: 463, text: "The analysis improves decision-making processes.", meaning: "Analiz karar verme süreçlerini iyileştirir.", category: "technical", type: "sentence" },
    { id: 464, text: "The system configuration was carefully selected.", meaning: "Sistem yapılandırması dikkatle seçildi.", category: "technical", type: "sentence" },
    { id: 465, text: "The results validate the proposed approach.", meaning: "Sonuçlar önerilen yaklaşımı doğrulamaktadır.", category: "technical", type: "sentence" },
    { id: 466, text: "The design minimizes operational risks.", meaning: "Tasarım operasyonel riskleri en aza indirir.", category: "technical", type: "sentence" },
    { id: 467, text: "The experiment highlights system limitations.", meaning: "Deney sistem sınırlamalarını ortaya koyar.", category: "technical", type: "sentence" },
    { id: 468, text: "The method improves system accuracy.", meaning: "Yöntem sistem doğruluğunu artırır.", category: "technical", type: "sentence" },
    { id: 469, text: "The system was evaluated under various scenarios.", meaning: "Sistem çeşitli senaryolar altında değerlendirildi.", category: "technical", type: "sentence" },
    { id: 470, text: "The results show consistent performance.", meaning: "Sonuçlar tutarlı performans göstermektedir.", category: "technical", type: "sentence" },
    { id: 471, text: "The design supports efficient system integration.", meaning: "Tasarım verimli sistem entegrasyonunu destekler.", category: "technical", type: "sentence" },
    { id: 472, text: "The experiment provides valuable data.", meaning: "Deney değerli veriler sağlar.", category: "technical", type: "sentence" },
    { id: 473, text: "The system performance meets expectations.", meaning: "Sistem performansı beklentileri karşılar.", category: "technical", type: "sentence" },
    { id: 474, text: "The analysis reveals critical system parameters.", meaning: "Analiz kritik sistem parametrelerini ortaya çıkarır.", category: "technical", type: "sentence" },
    { id: 475, text: "The method ensures reliable system operation.", meaning: "Yöntem güvenilir sistem çalışmasını sağlar.", category: "technical", type: "sentence" },
    { id: 476, text: "The system was designed for high efficiency.", meaning: "Sistem yüksek verimlilik için tasarlandı.", category: "technical", type: "sentence" },
    { id: 477, text: "The experiment supports future development.", meaning: "Deney gelecekteki geliştirmeleri destekler.", category: "technical", type: "sentence" },
    { id: 478, text: "The design process improves system quality.", meaning: "Tasarım süreci sistem kalitesini artırır.", category: "technical", type: "sentence" },
    { id: 479, text: "The results emphasize the importance of optimization.", meaning: "Sonuçlar optimizasyonun önemini vurgular.", category: "technical", type: "sentence" },
    { id: 480, text: "The system was tested for robustness.", meaning: "Sistem dayanıklılık açısından test edildi.", category: "technical", type: "sentence" },
    { id: 481, text: "The method contributes to efficient system design.", meaning: "Yöntem verimli sistem tasarımına katkı sağlar.", category: "technical", type: "sentence" },
    { id: 482, text: "The experiment confirms performance improvements.", meaning: "Deney performans iyileştirmelerini doğrular.", category: "technical", type: "sentence" },
    { id: 483, text: "The analysis focuses on system reliability.", meaning: "Analiz sistem güvenilirliğine odaklanır.", category: "technical", type: "sentence" },
    { id: 484, text: "The system operates under predefined conditions.", meaning: "Sistem önceden tanımlanmış koşullar altında çalışır.", category: "technical", type: "sentence" },
    { id: 485, text: "The results support the initial assumptions.", meaning: "Sonuçlar başlangıç varsayımlarını destekler.", category: "technical", type: "sentence" },
    { id: 486, text: "The design enhances system functionality.", meaning: "Tasarım sistem işlevselliğini artırır.", category: "technical", type: "sentence" },
    { id: 487, text: "The experiment identifies key performance factors.", meaning: "Deney temel performans faktörlerini belirler.", category: "technical", type: "sentence" },
    { id: 488, text: "The method improves overall system performance.", meaning: "Yöntem genel sistem performansını artırır.", category: "technical", type: "sentence" },
    { id: 489, text: "The system was analyzed for efficiency.", meaning: "Sistem verimlilik açısından analiz edildi.", category: "technical", type: "sentence" },
    { id: 490, text: "The results demonstrate method reliability.", meaning: "Sonuçlar yöntemin güvenilirliğini göstermektedir.", category: "technical", type: "sentence" },
    { id: 491, text: "The design process supports continuous improvement.", meaning: "Tasarım süreci sürekli iyileştirmeyi destekler.", category: "technical", type: "sentence" },
    { id: 492, text: "The experiment validates system performance.", meaning: "Deney sistem performansını doğrular.", category: "technical", type: "sentence" },
    { id: 493, text: "The analysis contributes to better system design.", meaning: "Analiz daha iyi sistem tasarımına katkı sağlar.", category: "technical", type: "sentence" },
    { id: 494, text: "The system meets all functional requirements.", meaning: "Sistem tüm işlevsel gereksinimleri karşılar.", category: "technical", type: "sentence" },
    { id: 495, text: "The results provide a basis for further studies.", meaning: "Sonuçlar ileri çalışmalar için bir temel sağlar.", category: "technical", type: "sentence" },
    { id: 496, text: "The design ensures long-term system stability.", meaning: "Tasarım uzun vadeli sistem kararlılığını sağlar.", category: "technical", type: "sentence" },
    { id: 497, text: "The experiment confirms the effectiveness of the method.", meaning: "Deney yöntemin etkinliğini doğrular.", category: "technical", type: "sentence" },
    { id: 498, text: "The system was optimized based on test results.", meaning: "Sistem test sonuçlarına göre optimize edildi.", category: "technical", type: "sentence" },
    { id: 499, text: "The analysis highlights critical design factors.", meaning: "Analiz kritik tasarım faktörlerini vurgular.", category: "technical", type: "sentence" },
    { id: 500, text: "The results demonstrate successful system implementation.", meaning: "Sonuçlar başarılı sistem uygulamasını göstermektedir.", category: "technical", type: "sentence" }

];

document.addEventListener('DOMContentLoaded', () => {
    if(localStorage.getItem('synapse-theme') === 'dark') toggleTheme();
    refreshUI();
    updateDateTime();
    setFunRecommendations();
    setInterval(updateDateTime, 60000);
});

function updateDateTime() {
    const now = new Date();
    const options = { day: 'numeric', month: 'long', year: 'numeric' };
    document.getElementById('current-date').innerText = now.toLocaleDateString('en-US', options);
    document.getElementById('current-time').innerText = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
}

function setFunRecommendations() {
    const musics = [
  "Interstellar Main Theme",
  "Hans Zimmer - Time",
  "Hans Zimmer - Cornfield Chase",
  "Hans Zimmer - Mountains",
  "Hans Zimmer - No Time for Caution",
  "Daft Punk - Contact",
  "Daft Punk - Derezzed",
  "Daft Punk - Solar Sailer",
  "Pink Floyd - Learning to Fly",
  "Pink Floyd - Time",
  "Pink Floyd - High Hopes",
  "Pink Floyd - Shine On You Crazy Diamond",
  "M83 - Outro",
  "M83 - Midnight City",
  "Ludovico Einaudi - Experience",
  "Ludovico Einaudi - Nuvole Bianche",
  "Max Richter - On The Nature of Daylight",
  "Max Richter - November",
  "Vangelis - Conquest of Paradise",
  "Vangelis - Blade Runner Blues",
  "Clint Mansell - Lux Aeterna",
  "Clint Mansell - Death Is the Road to Awe",
  "John Murphy - Adagio in D Minor",
  "Ramin Djawadi - Light of the Seven",
  "Ramin Djawadi - Westworld Main Theme",
  "Howard Shore - The Breaking of the Fellowship",
  "Ólafur Arnalds - Near Light",
  "Ólafur Arnalds - Saman",
  "Nils Frahm - Says",
  "Nils Frahm - My Friend the Forest",
  "Explosions in the Sky - Your Hand in Mine",
  "Explosions in the Sky - First Breath After Coma",
  "Trent Reznor & Atticus Ross - Hand Covers Bruise",
  "Trent Reznor & Atticus Ross - In Motion",
  "Jóhann Jóhannsson - Flight from the City",
  "Jóhann Jóhannsson - The Theory of Everything",
  "Hania Rani - F Major",
  "A Winged Victory for the Sullen - Steep Hills of Vicodin Tears",
  "Brian Eno - An Ending (Ascent)",
  "Brian Eno - Apollo: Atmospheres",
  "The Cinematic Orchestra - Arrival of the Birds",
  "The Cinematic Orchestra - To Build a Home",
  "Boards of Canada - Dayvan Cowboy",
  "Boards of Canada - Reach for the Dead",
  "Tycho - Awake",
  "Tycho - Horizon",
  "Dead Can Dance - The Host of Seraphim",
  "Two Steps From Hell - Heart of Courage",
  "Audiomachine - Blood and Stone"
];
const movies = [
  "Interstellar",
  "Inception",
  "The Imitation Game",
  "A Beautiful Mind",
  "The Theory of Everything",
  "Oppenheimer",
  "Arrival",
  "Ex Machina",
  "Blade Runner 2049",
  "The Martian",
  "Good Will Hunting",
  "The Social Network",
  "Her",
  "Gattaca",
  "Minority Report",
  "Matrix",
  "Matrix Reloaded",
  "Matrix Revolutions",
  "Tenet",
  "Moon",
  "Contact",
  "Gravity",
  "2001: A Space Odyssey",
  "Dune",
  "Dune Part Two",
  "Edge of Tomorrow",
  "District 9",
  "Elysium",
  "Chappie",
  "Source Code",
  "Predestination",
  "The Prestige",
  "Shutter Island",
  "Fight Club",
  "Se7en",
  "Whiplash",
  "Black Swan",
  "Ford v Ferrari",
  "Moneyball",
  "The Big Short",
  "Snowden",
  "Dark Waters",
  "The Founder",
  "Jobs",
  "Steve Jobs",
  "Apollo 13",
  "First Man",
  "October Sky",
  "Hidden Figures",
  "A.I. Artificial Intelligence"
];

    document.getElementById('daily-music').innerText = musics[Math.floor(Math.random() * musics.length)];
    document.getElementById('daily-movie').innerText = movies[Math.floor(Math.random() * movies.length)];
}

function updateStats() {
    const total = synapseDatabase.length;
    const techCount = synapseDatabase.filter(i => i.category === 'technical').length;
    const dailyCount = synapseDatabase.filter(i => i.category === 'daily').length;

    document.getElementById('stats-total').innerText = `Total: ${total}`;
    document.getElementById('stats-tech').innerText = `Tech: ${techCount}`;
    document.getElementById('stats-daily').innerText = `Daily: ${dailyCount}`;
}

function refreshUI() {
    const grid = document.getElementById('contentGrid');
    grid.innerHTML = '';
    
    let items = synapseDatabase;

    if (currentTab === 'tech-word') items = synapseDatabase.filter(i => i.category === 'technical' && i.type === 'word');
    else if (currentTab === 'tech-sentence') items = synapseDatabase.filter(i => i.category === 'technical' && i.type === 'sentence');
    else if (currentTab === 'daily-word') items = synapseDatabase.filter(i => i.category === 'daily' && i.type === 'word');
    else if (currentTab === 'daily-sentence') items = synapseDatabase.filter(i => i.category === 'daily' && i.type === 'sentence');

    items.forEach(item => {
        const card = document.createElement('div');
        card.className = `item-card ${item.category}`;
        card.innerHTML = `
            <small style="font-weight:700; color:var(--primary);">${item.category.toUpperCase()} ${item.type.toUpperCase()}</small>
            <h3 style="margin: 10px 0;">${item.text}</h3>
            <p>${item.meaning}</p>
        `;
        grid.appendChild(card);
    });

    updateStats();
}

function switchTab(tab) {
    currentTab = tab;
    document.querySelectorAll('.nav-item').forEach(b => b.classList.remove('active'));
    document.getElementById(`btn-${tab}`).classList.add('active');
    refreshUI();
}

function searchItems() {
    const q = document.getElementById('searchInput').value.toLowerCase();
    document.querySelectorAll('.item-card').forEach(c => {
        c.style.display = c.innerText.toLowerCase().includes(q) ? 'block' : 'none';
    });
}

function toggleTheme() {
    document.body.classList.toggle('dark-theme');
    const isDark = document.body.classList.contains('dark-theme');
    localStorage.setItem('synapse-theme', isDark ? 'dark' : 'light');
    document.getElementById('theme-toggle').innerHTML = isDark ? '<i class="fas fa-sun"></i> Light Mode' : '<i class="fas fa-moon"></i> Dark Mode';
}

// Scroll Handling for Back to Top
window.onscroll = function() {
    const btn = document.getElementById("backToTop");
    if (document.body.scrollTop > 300 || document.documentElement.scrollTop > 300) {
        btn.style.display = "block";
    } else {
        btn.style.display = "none";
    }
};

function scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
}